name: Check and Build

on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:

jobs:
  check_and_build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the remote repository
      uses: actions/checkout@v3
      with:
        repository: GNOME/msitools
        path: remote-repo

    - name: Get latest version
      id: latest_version
      run: |
        cd remote-repo
        git fetch --tags
        LATEST_VERSION=$(git describe --tags --abbrev=0 --always) || echo "Failed to get the latest version"
        echo "Latest version: $LATEST_VERSION"
        if [ -n "$LATEST_VERSION" ]; then
          echo "LATEST_VERSION=$LATEST_VERSION" >> $GITHUB_ENV
        else
          echo "Could not determine the latest version"
          exit 1
        fi