name: Check and Build

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  check_and_build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the remote repository
      uses: actions/checkout@v3
      with:
        repository: GNOME/msitools
        path: remote-repo

    - name: Get latest version
      id: latest_version
      run: |
        cd remote-repo
        git fetch --tags
        LATEST_VERSION=$(git tag | sort -V -r | head -n 1) || echo "Failed to get the latest version"
        echo "Latest version: $LATEST_VERSION"
        if [ -n "$LATEST_VERSION" ]; then
          echo "LATEST_VERSION=$LATEST_VERSION" >> $GITHUB_ENV
        else
          echo "Could not determine the latest version"
          exit 1
        fi

    - name: Set last version
      run: |
        LAST_VERSION="v0.100"
        echo "LAST_VERSION=$LAST_VERSION" >> $GITHUB_ENV

    - name: Compare versions and run script if needed
      run: |
        if [[ "${{ env.LATEST_VERSION }}" > "${{ env.LAST_VERSION }}" ]]; then
          echo "Updating from ${{ env.LAST_VERSION }} to ${{ env.LATEST_VERSION }}"
          # Run your script here
          #./my_script.sh
          # Add your release steps here
        else
          echo "Latest version (${{ env.LATEST_VERSION }}) is not greater than the last version (${{ env.LAST_VERSION }})"
        fi