name: Check and Build

on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:

jobs:
  check_and_build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the remote repository
      uses: actions/checkout@v2
      with:
        repository: GNOME/msitools
        path: remote-repo

    - name: Get latest version
      id: latest_version
      run: |
        cd remote-repo
        LATEST_VERSION=$(git describe --tags --abbrev=0)
        echo "LATEST_VERSION=$LATEST_VERSION" >> $GITHUB_ENV