name: Tests

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the appimage-builder repository
      uses: actions/checkout@v3
      with:
        repository: AppImageCrafters/appimage-builder
        path: remote-repo

    - name: Get latest appimage-builder version
      id: appimgbld_latest_version
      run: |
        cd remote-repo
        git fetch --tags
        AIB_LATEST_VERSION=$(git tag | sort -V -r | head -n 1) || echo "Failed to get the latest version"
        echo "Latest version: $AIB_LATEST_VERSION"
        if [ -n "$AIB_LATEST_VERSION" ]; then
          echo "AIB_LATEST_VERSION=$AIB_LATEST_VERSION" >> $GITHUB_ENV
        else
          echo "Could not determine the appimage-builder latest version"
          exit 1
        fi
