name: Tests

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the remote repository
      uses: actions/checkout@v3
      with:
        repository: GNOME/msitools
        path: remote-repo

    - name: Running test...
      id: running_test
      run: |
        echo "Listing GPGs..."
        ls -lah /etc/apt/trusted.gpg.d
        ls -lah /usr/share/keyrings
        echo "Listing Sources..."
        ls -lah /etc/apt/sources.list.d
        cat /etc/apt/sources.list.d/microsoft-prod.list
        cat /etc/apt/sources.list.d/ubuntu-toolchain-r-ubuntu-test-jammy.list