name: Tests

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Running test...
      id: running_test
      run: |
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 871920D1991BC93C
        echo "Listing GPGs..."
        ls -lah /etc/apt/trusted.gpg.d
        ls -lah /usr/share/keyrings
        echo "Listing Sources..."
        ls -lah /etc/apt/sources.list.d
        cat /etc/apt/sources.list.d/microsoft-prod.list
        cat /etc/apt/sources.list.d/ubuntu-toolchain-r-ubuntu-test-jammy.list    

    - name: Set last version
      run: |
        LAST_VERSION="v0.100"
        echo "LAST_VERSION=$LAST_VERSION" >> $GITHUB_ENV    

    # - name: Commit and push changes
    #   run: |
    #     git config --local user.email "action@github.com"
    #     git config --local user.name "GitHub Action"
    #     git add dist/msitools-$LATEST_VERSION-portable.tar.gz
    #     git commit -m "Add AppImageBuilder.yml file"
    #     git push
